leftnav:
- identifier: 7bb44a3f-b5fa-87e5-8c8b-470f32fa7287
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: cd6a2651-8973-6574-06dc-2da5b7df0b50
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 3b3ea632-e715-f038-d156-b400d19c1750
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 1a7120c6-2fd4-fdbc-ba6f-219a57f98f87
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 9d14f283-538f-4ded-bc93-581a5d6a3616
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
